# TORCH

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
# Version Torch Check
torch.__version__

'2.8.0+cu126'

## SCALAR
Scalar a single number of dimenstion usually with lower in variable

In [ ]:
# Scalar value nilai tunggal
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

## Vector

Vector is a number with a direction and have many other number that represent an value of feature or etc

In [ ]:
# Vector kumpulan nilai dalam 1d yang linear atau kalau di python list
vector = torch.tensor([1,2,3])
vector

tensor([1, 2, 3])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([3])

## MATRIX

MATRIX is a 2 dimensional array of number

In [5]:
MATRIX = torch.Tensor([ [1,2,3],
                        [4,5,6],
                        [7,8,9] ])

In [6]:
MATRIX.ndim

2

In [7]:
MATRIX.shape

torch.Size([3, 3])

## TENSOR

Tensor is an N dimensional array of numbers all of the term before is also can be called as tensor. <br>
EX: <br>


*   Scalar is 0-dim of tensor
*   Vector is 1-dim of tensor
*   Matrix is 2-dim of tensor



In [8]:
TENSOR = torch.Tensor([[ [1,2,3],
                        [4,5,6],
                        [7,8,9] ]])

TENSOR.ndim, TENSOR.shape

(3, torch.Size([1, 3, 3]))

### RANDOM TENSOR INITIATE

RANDOM tensors are important because neural networks using the random initial number to represent the amount and huge of the data.

In [20]:
random_tensor = torch.rand(10,10)
random_tensor

tensor([[0.4365, 0.3873, 0.2604, 0.9701, 0.9315, 0.3406, 0.4098, 0.8133, 0.9658,
         0.8247],
        [0.1584, 0.8986, 0.5622, 0.6879, 0.4928, 0.9155, 0.6775, 0.3508, 0.0298,
         0.3838],
        [0.3699, 0.8595, 0.4191, 0.8391, 0.6565, 0.0285, 0.2417, 0.8441, 0.4976,
         0.7637],
        [0.8802, 0.0482, 0.8720, 0.2166, 0.1306, 0.7419, 0.4762, 0.7037, 0.3049,
         0.9816],
        [0.8770, 0.4081, 0.6996, 0.3231, 0.3010, 0.9489, 0.3809, 0.3895, 0.4412,
         0.6203],
        [0.9646, 0.1684, 0.5788, 0.7412, 0.9978, 0.1732, 0.6706, 0.5505, 0.0136,
         0.4038],
        [0.8692, 0.3957, 0.8756, 0.2957, 0.9468, 0.2393, 0.7641, 0.1077, 0.0572,
         0.7923],
        [0.9735, 0.1989, 0.9704, 0.1607, 0.1238, 0.3934, 0.6942, 0.4195, 0.2819,
         0.6141],
        [0.9910, 0.4676, 0.0071, 0.4436, 0.2861, 0.2050, 0.7849, 0.8691, 0.2553,
         0.2325],
        [0.9974, 0.5674, 0.4583, 0.4508, 0.8605, 0.2494, 0.9811, 0.5372, 0.8462,
         0.1667]])

In [22]:
# EXAMPLE OF RANDOM IMAGE WITH 224 224 RGB
random_image_tensor = torch.rand(3, 224, 224) # HEIGHT WEIGHT COLOR CHANNEL
random_image_tensor

tensor([[[0.6282, 0.7946, 0.6269,  ..., 0.1642, 0.2375, 0.5675],
         [0.7334, 0.4941, 0.8464,  ..., 0.8848, 0.2784, 0.8740],
         [0.4449, 0.2748, 0.5980,  ..., 0.5892, 0.3923, 0.4830],
         ...,
         [0.7187, 0.6937, 0.3216,  ..., 0.5593, 0.9456, 0.2024],
         [0.2219, 0.1578, 0.9274,  ..., 0.8551, 0.8204, 0.8297],
         [0.0415, 0.5628, 0.7198,  ..., 0.4525, 0.3709, 0.7918]],

        [[0.8255, 0.4321, 0.2731,  ..., 0.0264, 0.8170, 0.1365],
         [0.9694, 0.9003, 0.4333,  ..., 0.0636, 0.0376, 0.0540],
         [0.6528, 0.6119, 0.8971,  ..., 0.9871, 0.4458, 0.3293],
         ...,
         [0.9981, 0.4543, 0.8656,  ..., 0.0732, 0.2314, 0.7950],
         [0.2533, 0.7340, 0.9198,  ..., 0.1127, 0.9428, 0.3061],
         [0.4085, 0.1995, 0.1788,  ..., 0.0409, 0.1366, 0.8953]],

        [[0.6576, 0.2949, 0.7219,  ..., 0.0353, 0.1543, 0.0149],
         [0.2100, 0.2042, 0.7840,  ..., 0.6474, 0.4700, 0.1085],
         [0.0808, 0.1999, 0.7646,  ..., 0.0074, 0.1245, 0.

In [25]:
# CREATING ZEROS TENSOR AND ONES

zeros_tensor = torch.zeros(3,4)
one_tensor_value = torch.ones(3,4)
zeros_tensor, one_tensor_value

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))