# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch
print(torch.__version__)
# Create random tensor
rand_tensor = torch.rand(7,7)
rand_tensor

2.8.0+cu126


tensor([[0.4110, 0.7326, 0.9006, 0.7262, 0.3238, 0.0765, 0.6035],
        [0.9808, 0.4509, 0.4633, 0.0530, 0.9802, 0.0019, 0.2866],
        [0.4808, 0.8966, 0.1113, 0.4213, 0.0771, 0.7708, 0.9280],
        [0.8161, 0.2722, 0.8969, 0.9558, 0.0838, 0.8569, 0.5478],
        [0.7639, 0.3022, 0.8160, 0.8015, 0.2697, 0.0255, 0.4007],
        [0.9851, 0.9507, 0.3438, 0.7112, 0.3298, 0.6653, 0.1724],
        [0.2653, 0.5374, 0.5787, 0.1701, 0.6487, 0.5129, 0.4689]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
new_rand_tensor = torch.rand(1,7)
print(new_rand_tensor)
# Perform matrix multiplication
rand_tensor @ new_rand_tensor.T

tensor([[0.9283, 0.9699, 0.4359, 0.1775, 0.4486, 0.8979, 0.6040]])


tensor([[2.1920],
        [2.1737],
        [2.7264],
        [2.7201],
        [1.8861],
        [2.9620],
        [2.0847]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
rand_tensor = torch.rand(7,7)
new_rand_tensor = torch.rand(1,7)
# Matrix multiply tensors
matmul_tensor = rand_tensor @ new_rand_tensor.T
matmul_tensor, matmul_tensor.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [12]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [14]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
print(torch.cuda.is_available())
# Create two random tensors on GPU
tensor_1 = torch.rand(2,3).cuda()
tensor_2 = torch.rand(2,3).cuda()
tensor_1, tensor_2

True


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [17]:
# Perform matmul on tensor_A and tensor_B
matmul_tensor_result = tensor_1 @ tensor_2.T
matmul_tensor_result, matmul_tensor_result.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [18]:
# Find max
print(matmul_tensor_result.max())
# Find min
torch.min(matmul_tensor_result)

tensor(0.5617, device='cuda:0')


tensor(0.3647, device='cuda:0')

### 9. Find the maximum and minimum index values of the output of 7.

In [19]:
# Find arg max
print(matmul_tensor_result.argmax())

# Find arg min
torch.argmin(matmul_tensor_result)

tensor(3, device='cuda:0')


tensor(0, device='cuda:0')


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [20]:
# Set seed
torch.manual_seed(7)

# Create random tensor
new_tensor = torch.rand(1,1,1,10)
print(f"Tensor Before: {new_tensor}")
# Remove single dimensions
new_tensor = new_tensor.squeeze()

# Print out tensors and their shapes
new_tensor, new_tensor.shape

Tensor Before: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])


(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))